# this file should be put in /etc/nginx/sites-available
# https://www.scaleway.com/en/docs/tutorials/nginx-reverse-proxy/
server {
    listen 80;
    listen [::]:80;

    client_max_body_size 20M;

    access_log /var/log/nginx/reverse-proxy-access.log;
    error_log /var/log/nginx/reverse-proxy-error.log;

    location / {
        proxy_pass http://{FRONT_END_HOST:PORT};
    }

    location /api/ {
        rewrite    /api/(.*) /$1 break;
        proxy_pass http://{BACK_END_HOST:PORT};
    }
}